language: node_js
node_js:
  - "8"
# for node_js, by default install lifecycle runs
# `npm install`, so run linting/testing after in
# the `before_script` lifecycle
before_script:
  - npm run lint
  - npm run flow
script:
  - npm run build
# TODO: Add you deploy settings here
# deploy:
#     provider: script
#     script: ./deploy.sh
#     skip_cleanup: true
cache:
    directories:
        - node_modules
# only trigger build when commit to master branch
branches:
  only:
    - master
